-- =====================================================================================
-- Kuda putujem — inicijalna šema
-- =====================================================================================

CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS btree_gist;

-- Nedeterministički unaccent ne sme u indeks; pravimo IMMUTABLE omotač.
--
-- Đ/đ se zamenjuje RUČNO pre unaccent-a: unaccent daje 'd', a srpska
-- transliteracija je 'dj'. Python `normalize()` radi isto — test
-- tests/test_sql_parity.py to proverava.
CREATE OR REPLACE FUNCTION norm_text(input text)
    RETURNS text
    LANGUAGE sql
    IMMUTABLE
    PARALLEL SAFE
    STRICT
AS $$
SELECT btrim(
    regexp_replace(
        lower(
            public.unaccent(
                'public.unaccent',
                replace(replace(input, 'đ', 'dj'), 'Đ', 'Dj')
            )
        ),
        '[^a-z0-9]+', ' ', 'g'
    )
);
$$;

-- =====================================================================================
-- 1. Agencije i izvori
-- =====================================================================================

CREATE TABLE agency
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug            TEXT        NOT NULL UNIQUE,
    name            TEXT        NOT NULL,
    legal_name      TEXT,
    website_url     TEXT        NOT NULL,
    logo_url        TEXT,
    licence_number  TEXT,                                   -- OTP / OPG licenca
    country_code    CHAR(2)     NOT NULL DEFAULT 'RS',
    city            TEXT,
    phone           TEXT,
    email           TEXT,
    -- šta agencija uopšte nudi; koristi se za filtriranje u adminu
    product_kinds   TEXT[]      NOT NULL DEFAULT '{}',      -- PACKAGE / TRANSPORT / ACCOMMODATION
    is_active       BOOLEAN     NOT NULL DEFAULT TRUE,
    notes           TEXT,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE source
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    agency_id         BIGINT      NOT NULL REFERENCES agency (id) ON DELETE CASCADE,
    slug              TEXT        NOT NULL UNIQUE,          -- npr. travelland-letovanje
    label             TEXT        NOT NULL,
    base_url          TEXT        NOT NULL,
    adapter_key       TEXT        NOT NULL,                 -- ime Python adaptera
    product_kind      TEXT        NOT NULL,                 -- PACKAGE / TRANSPORT / ACCOMMODATION
    config            JSONB       NOT NULL DEFAULT '{}'::jsonb,
    -- pristojnost
    robots_allowed    BOOLEAN     NOT NULL DEFAULT TRUE,
    crawl_delay_ms    INT         NOT NULL DEFAULT 2000,
    max_concurrency   INT         NOT NULL DEFAULT 2,
    requires_browser  BOOLEAN     NOT NULL DEFAULT FALSE,
    -- raspored i zdravlje
    schedule_cron     TEXT        NOT NULL DEFAULT '0 30 3 * * *',
    is_enabled        BOOLEAN     NOT NULL DEFAULT TRUE,
    health_status     TEXT        NOT NULL DEFAULT 'UNKNOWN', -- OK/DEGRADED/FAILING/DISABLED/UNKNOWN
    expected_min_items INT        NOT NULL DEFAULT 1,
    last_run_at       TIMESTAMPTZ,
    last_success_at   TIMESTAMPTZ,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_source_agency ON source (agency_id);
CREATE INDEX idx_source_enabled ON source (is_enabled) WHERE is_enabled;

CREATE TABLE crawl_run
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id      BIGINT      NOT NULL REFERENCES source (id) ON DELETE CASCADE,
    status         TEXT        NOT NULL DEFAULT 'RUNNING',  -- RUNNING/OK/SUSPECT/FAILED/CANCELLED
    trigger_kind   TEXT        NOT NULL DEFAULT 'SCHEDULED',-- SCHEDULED/MANUAL/RETRY
    started_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    finished_at    TIMESTAMPTZ,
    pages_fetched  INT         NOT NULL DEFAULT 0,
    items_found    INT         NOT NULL DEFAULT 0,
    items_created  INT         NOT NULL DEFAULT 0,
    items_updated  INT         NOT NULL DEFAULT 0,
    items_failed   INT         NOT NULL DEFAULT 0,
    items_expired  INT         NOT NULL DEFAULT 0,
    error_message  TEXT,
    stats          JSONB       NOT NULL DEFAULT '{}'::jsonb,
    scraper_version TEXT
);
CREATE INDEX idx_crawl_run_source_started ON crawl_run (source_id, started_at DESC);

-- Sirovi snapshot; služi za ponovno parsiranje bez novog zahteva i za dokazivanje šta je sajt vratio.
CREATE TABLE raw_document
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crawl_run_id  BIGINT      NOT NULL REFERENCES crawl_run (id) ON DELETE CASCADE,
    source_id     BIGINT      NOT NULL REFERENCES source (id) ON DELETE CASCADE,
    url           TEXT        NOT NULL,
    http_status   INT         NOT NULL,
    content_type  TEXT,
    content_hash  TEXT        NOT NULL,
    body          BYTEA,                                     -- gzip
    body_size     INT         NOT NULL DEFAULT 0,
    fetched_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_raw_document_run ON raw_document (crawl_run_id);
CREATE INDEX idx_raw_document_hash ON raw_document (source_id, content_hash);
CREATE INDEX idx_raw_document_fetched ON raw_document (fetched_at);

-- =====================================================================================
-- 2. Geografija
-- =====================================================================================

CREATE TABLE destination
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    parent_id     BIGINT REFERENCES destination (id) ON DELETE SET NULL,
    kind          TEXT        NOT NULL,                     -- COUNTRY/REGION/CITY/RESORT/ISLAND
    slug          TEXT        NOT NULL UNIQUE,
    name_sr       TEXT        NOT NULL,
    name_en       TEXT,
    country_code  CHAR(2)     NOT NULL,
    latitude      DOUBLE PRECISION,
    longitude     DOUBLE PRECISION,
    is_active     BOOLEAN     NOT NULL DEFAULT TRUE,
    is_departure_hub BOOLEAN  NOT NULL DEFAULT FALSE,       -- mesto polaska u Srbiji
    is_ski        BOOLEAN     NOT NULL DEFAULT FALSE,       -- ski centar
    popularity    INT         NOT NULL DEFAULT 0,           -- za sortiranje autocomplete-a
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_destination_parent ON destination (parent_id);
CREATE INDEX idx_destination_country ON destination (country_code);
CREATE INDEX idx_destination_name_trgm ON destination USING gin (norm_text(name_sr) gin_trgm_ops);

-- Sirova imena sa sajtova → kanonska destinacija.
CREATE TABLE destination_alias
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT REFERENCES destination (id) ON DELETE CASCADE,
    source_id      BIGINT REFERENCES source (id) ON DELETE CASCADE,
    raw_name       TEXT        NOT NULL,
    normalized     TEXT        NOT NULL,
    confidence     NUMERIC(4, 3) NOT NULL DEFAULT 1.000,
    status         TEXT        NOT NULL DEFAULT 'CONFIRMED',-- CONFIRMED/PENDING/REJECTED
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_destination_alias ON destination_alias (normalized, COALESCE(source_id, 0));
CREATE INDEX idx_destination_alias_pending ON destination_alias (status) WHERE status = 'PENDING';

-- =====================================================================================
-- 3. Smeštajni objekti
-- =====================================================================================

CREATE TABLE accommodation
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    destination_id BIGINT REFERENCES destination (id) ON DELETE SET NULL,
    slug           TEXT        NOT NULL UNIQUE,
    name           TEXT        NOT NULL,
    kind           TEXT        NOT NULL DEFAULT 'HOTEL',    -- HOTEL/APARTMENT/VILLA/HOSTEL/RESORT/ROOM/CAMP
    stars          NUMERIC(2, 1),
    address        TEXT,
    latitude       DOUBLE PRECISION,
    longitude      DOUBLE PRECISION,
    distance_to_beach_m INT,
    description    TEXT,
    amenities      JSONB       NOT NULL DEFAULT '[]'::jsonb,
    images         JSONB       NOT NULL DEFAULT '[]'::jsonb,
    rating_avg     NUMERIC(3, 2),
    rating_count   INT         NOT NULL DEFAULT 0,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_accommodation_destination ON accommodation (destination_id);
CREATE INDEX idx_accommodation_name_trgm ON accommodation USING gin (norm_text(name) gin_trgm_ops);

CREATE TABLE accommodation_alias
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    accommodation_id BIGINT REFERENCES accommodation (id) ON DELETE CASCADE,
    source_id        BIGINT REFERENCES source (id) ON DELETE CASCADE,
    external_id      TEXT,
    raw_name         TEXT        NOT NULL,
    normalized       TEXT        NOT NULL,
    confidence       NUMERIC(4, 3) NOT NULL DEFAULT 1.000,
    status           TEXT        NOT NULL DEFAULT 'CONFIRMED',
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE UNIQUE INDEX uq_accommodation_alias ON accommodation_alias (normalized, COALESCE(source_id, 0));
CREATE INDEX idx_accommodation_alias_pending ON accommodation_alias (status) WHERE status = 'PENDING';

-- =====================================================================================
-- 4. Ponude
-- =====================================================================================

CREATE TABLE offer
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id        BIGINT      NOT NULL REFERENCES source (id) ON DELETE CASCADE,
    agency_id        BIGINT      NOT NULL REFERENCES agency (id) ON DELETE CASCADE,
    external_id      TEXT        NOT NULL,                   -- stabilan ID sa sajta agencije
    product_kind     TEXT        NOT NULL,                   -- PACKAGE/TRANSPORT/ACCOMMODATION
    title            TEXT        NOT NULL,
    slug             TEXT        NOT NULL,
    url              TEXT        NOT NULL,                   -- deep link ka agenciji
    -- šta se nudi
    accommodation_id BIGINT REFERENCES accommodation (id) ON DELETE SET NULL,
    destination_id   BIGINT REFERENCES destination (id) ON DELETE SET NULL,
    country_code     CHAR(2),
    transport_type   TEXT        NOT NULL DEFAULT 'NONE',    -- BUS/PLANE/OWN/TRAIN/FERRY/MINIVAN/NONE
    board_type       TEXT        NOT NULL DEFAULT 'NONE',    -- RO/BB/HB/FB/AI/UAI/NONE
    -- opis
    description      TEXT,
    images           JSONB       NOT NULL DEFAULT '[]'::jsonb,
    highlights       JSONB       NOT NULL DEFAULT '[]'::jsonb,
    included         JSONB       NOT NULL DEFAULT '[]'::jsonb,
    not_included     JSONB       NOT NULL DEFAULT '[]'::jsonb,
    raw_attributes   JSONB       NOT NULL DEFAULT '{}'::jsonb,
    -- tržište i valuta
    market           CHAR(2)     NOT NULL DEFAULT 'RS',
    currency         CHAR(3)     NOT NULL DEFAULT 'EUR',
    -- denormalizacija za brzu pretragu / sortiranje
    min_price_rsd    NUMERIC(12, 2),
    min_nights       INT,
    max_nights       INT,
    first_departure  DATE,
    last_departure   DATE,
    departure_count  INT         NOT NULL DEFAULT 0,
    -- životni ciklus
    content_hash     TEXT        NOT NULL,
    is_active        BOOLEAN     NOT NULL DEFAULT TRUE,
    first_seen_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_seen_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    last_changed_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
    CONSTRAINT uq_offer_source_external UNIQUE (source_id, external_id)
);
CREATE INDEX idx_offer_active_kind ON offer (product_kind, is_active) WHERE is_active;
CREATE INDEX idx_offer_destination ON offer (destination_id) WHERE is_active;
CREATE INDEX idx_offer_accommodation ON offer (accommodation_id) WHERE is_active;
CREATE INDEX idx_offer_agency ON offer (agency_id);
CREATE INDEX idx_offer_source ON offer (source_id);
CREATE INDEX idx_offer_min_price ON offer (min_price_rsd) WHERE is_active;
CREATE INDEX idx_offer_title_trgm ON offer USING gin (norm_text(title) gin_trgm_ops);

-- Konkretan termin. Za ACCOMMODATION izvore ovo je slobodan opseg (check-in dan po danu).
CREATE TABLE departure
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id            BIGINT      NOT NULL REFERENCES offer (id) ON DELETE CASCADE,
    external_id         TEXT,
    start_date          DATE        NOT NULL,
    end_date            DATE        NOT NULL,
    nights              INT         NOT NULL,
    days                INT,
    transport_type      TEXT        NOT NULL DEFAULT 'NONE',
    departure_place_id  BIGINT REFERENCES destination (id) ON DELETE SET NULL,
    departure_place_raw TEXT,                                -- "Beograd", "Niš", "Novi Sad"
    board_type          TEXT,
    is_available        BOOLEAN     NOT NULL DEFAULT TRUE,
    seats_left          INT,
    is_last_minute      BOOLEAN     NOT NULL DEFAULT FALSE,
    -- denormalizacija
    min_price           NUMERIC(12, 2),
    min_price_rsd       NUMERIC(12, 2),
    currency            CHAR(3)     NOT NULL DEFAULT 'EUR',
    last_seen_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at          TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_departure_offer ON departure (offer_id);
CREATE INDEX idx_departure_dates ON departure (start_date, end_date) WHERE is_available;
CREATE INDEX idx_departure_offer_start ON departure (offer_id, start_date);
CREATE UNIQUE INDEX uq_departure_natural ON departure (offer_id, start_date, end_date, COALESCE(departure_place_raw, ''));

-- Cena za jednu kombinaciju sobe / slota. Ovo je srce domena.
--
-- Primeri iz stvarnosti:
--   "1/2 — 349 EUR po osobi"            → room_code=1/2,   capacity_adults=2, slot=ADULT,  basis=PER_PERSON_PER_STAY
--   "1/2+1 dete do 12 — 199 EUR"        → room_code=1/2+1, capacity_adults=2, extra_beds=1, slot=CHILD, child_age_to=11
--   "Apartman A2/4 — 60 EUR po danu"    → room_code=A2/4,  capacity_total=4, slot=UNIT,   basis=PER_UNIT_PER_NIGHT
CREATE TABLE price_option
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    departure_id      BIGINT      NOT NULL REFERENCES departure (id) ON DELETE CASCADE,
    offer_id          BIGINT      NOT NULL REFERENCES offer (id) ON DELETE CASCADE,
    -- opis sobe
    room_code         TEXT        NOT NULL,                  -- sirovo, kako piše agencija
    room_name         TEXT,
    capacity_adults   INT         NOT NULL DEFAULT 2,
    capacity_extra    INT         NOT NULL DEFAULT 0,        -- pomoćni ležajevi
    capacity_total    INT         NOT NULL DEFAULT 2,
    -- šta se plaća
    slot              TEXT        NOT NULL DEFAULT 'ADULT',  -- ADULT/CHILD/INFANT/EXTRA_BED/UNIT/SINGLE_SUPPLEMENT
    pricing_basis     TEXT        NOT NULL DEFAULT 'PER_PERSON_PER_STAY',
                                                             -- PER_PERSON_PER_STAY / PER_PERSON_PER_NIGHT
                                                             -- PER_UNIT_PER_STAY   / PER_UNIT_PER_NIGHT
    board_type        TEXT,
    child_age_from    INT,
    child_age_to      INT,
    -- iznos
    amount            NUMERIC(12, 2) NOT NULL,
    amount_rsd        NUMERIC(12, 2),
    currency          CHAR(3)     NOT NULL DEFAULT 'EUR',
    original_amount   NUMERIC(12, 2),                        -- cena pre popusta, ako je istaknuta
    discount_label    TEXT,                                  -- "first minute", "-20%"
    is_promo          BOOLEAN     NOT NULL DEFAULT FALSE,
    -- meta
    min_stay_nights   INT,
    notes             TEXT,
    last_seen_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_price_option_departure ON price_option (departure_id);
CREATE INDEX idx_price_option_offer ON price_option (offer_id);

-- Doplate koje agencija ne uračunava u istaknutu cenu (boravišna taksa, osiguranje, gorivo, prevoz).
CREATE TABLE surcharge
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id      BIGINT      NOT NULL REFERENCES offer (id) ON DELETE CASCADE,
    departure_id  BIGINT REFERENCES departure (id) ON DELETE CASCADE,
    code          TEXT,                                      -- TOURIST_TAX/INSURANCE/TRANSPORT/FUEL/LOCAL_FEE/OTHER
    name          TEXT        NOT NULL,
    kind          TEXT        NOT NULL DEFAULT 'MANDATORY',  -- MANDATORY/OPTIONAL
    unit          TEXT        NOT NULL DEFAULT 'PER_PERSON', -- PER_PERSON/PER_PERSON_PER_NIGHT/PER_UNIT/PER_BOOKING
    amount        NUMERIC(12, 2),
    currency      CHAR(3),
    payable       TEXT        NOT NULL DEFAULT 'IN_ADVANCE', -- IN_ADVANCE/ON_SITE
    raw_text      TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_surcharge_offer ON surcharge (offer_id);
CREATE INDEX idx_surcharge_departure ON surcharge (departure_id);

-- Deonice putovanja za samostalan prevoz (autobus, avion, voz).
CREATE TABLE transport_leg
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id          BIGINT      NOT NULL REFERENCES offer (id) ON DELETE CASCADE,
    departure_id      BIGINT REFERENCES departure (id) ON DELETE CASCADE,
    leg_index         INT         NOT NULL DEFAULT 0,
    direction         TEXT        NOT NULL DEFAULT 'OUTBOUND', -- OUTBOUND/RETURN
    mode              TEXT        NOT NULL,                  -- BUS/PLANE/TRAIN/FERRY/MINIVAN
    carrier_name      TEXT,
    carrier_code      TEXT,
    vehicle_number    TEXT,                                  -- broj leta / linije
    from_place_id     BIGINT REFERENCES destination (id) ON DELETE SET NULL,
    from_place_raw    TEXT        NOT NULL,
    from_terminal     TEXT,
    to_place_id       BIGINT REFERENCES destination (id) ON DELETE SET NULL,
    to_place_raw      TEXT        NOT NULL,
    to_terminal       TEXT,
    depart_at         TIMESTAMPTZ,
    arrive_at         TIMESTAMPTZ,
    depart_local      TEXT,                                  -- kad sajt daje samo "07:30"
    arrive_local      TEXT,
    duration_minutes  INT,
    stops             INT         NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_transport_leg_offer ON transport_leg (offer_id);
CREATE INDEX idx_transport_leg_departure ON transport_leg (departure_id);

-- =====================================================================================
-- 5. Denormalizovani indeks cena za pretragu
--    Jedan red po (departure, broj odraslih). Puni ga job posle svake ingest runde.
-- =====================================================================================

CREATE TABLE departure_price_index
(
    departure_id   BIGINT      NOT NULL REFERENCES departure (id) ON DELETE CASCADE,
    offer_id       BIGINT      NOT NULL REFERENCES offer (id) ON DELETE CASCADE,
    pax            SMALLINT    NOT NULL,                     -- 1..8 odraslih
    rooms_used     SMALLINT    NOT NULL,
    total_amount   NUMERIC(12, 2) NOT NULL,
    total_rsd      NUMERIC(12, 2) NOT NULL,
    per_person_rsd NUMERIC(12, 2) NOT NULL,
    currency       CHAR(3)     NOT NULL,
    plan           JSONB       NOT NULL DEFAULT '[]'::jsonb, -- [{room_code, count, capacity}]
    computed_at    TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (departure_id, pax)
);
CREATE INDEX idx_dpi_search ON departure_price_index (pax, total_rsd);
CREATE INDEX idx_dpi_offer ON departure_price_index (offer_id, pax);

-- =====================================================================================
-- 6. Kursna lista (za sortiranje po ceni u RSD)
-- =====================================================================================

CREATE TABLE exchange_rate
(
    rate_date  DATE        NOT NULL,
    currency   CHAR(3)     NOT NULL,
    rate_rsd   NUMERIC(12, 6) NOT NULL,                      -- koliko RSD za 1 jedinicu valute
    source     TEXT        NOT NULL DEFAULT 'NBS',
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (rate_date, currency)
);

-- =====================================================================================
-- 7. Lead-ovi (upiti korisnika)
-- =====================================================================================

CREATE TABLE lead
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id            UUID        NOT NULL DEFAULT gen_random_uuid() UNIQUE,
    offer_id             BIGINT REFERENCES offer (id) ON DELETE SET NULL,
    departure_id         BIGINT REFERENCES departure (id) ON DELETE SET NULL,
    agency_id            BIGINT REFERENCES agency (id) ON DELETE SET NULL,
    -- podaci korisnika
    full_name            TEXT        NOT NULL,
    email                TEXT        NOT NULL,
    phone                TEXT,
    message              TEXT,
    -- šta traži
    adults               INT         NOT NULL DEFAULT 2,
    children_ages        INT[]       NOT NULL DEFAULT '{}',
    room_plan            JSONB       NOT NULL DEFAULT '[]'::jsonb,
    date_from            DATE,
    date_to              DATE,
    quoted_amount        NUMERIC(12, 2),
    quoted_currency      CHAR(3),
    -- saglasnost (ZZPL / GDPR)
    consent_marketing    BOOLEAN     NOT NULL DEFAULT FALSE,
    consent_text_version TEXT        NOT NULL,
    consent_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    ip_hash              TEXT,
    user_agent           TEXT,
    -- obrada
    status               TEXT        NOT NULL DEFAULT 'NEW', -- NEW/SENT/FAILED/CONTACTED/CLOSED/SPAM
    sent_at              TIMESTAMPTZ,
    error_message        TEXT,
    delete_after         DATE,                               -- rok čuvanja
    created_at           TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_lead_status ON lead (status, created_at DESC);
CREATE INDEX idx_lead_agency ON lead (agency_id, created_at DESC);
CREATE INDEX idx_lead_delete_after ON lead (delete_after) WHERE delete_after IS NOT NULL;

CREATE TABLE lead_event
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    lead_id    BIGINT      NOT NULL REFERENCES lead (id) ON DELETE CASCADE,
    kind       TEXT        NOT NULL,
    payload    JSONB       NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_lead_event_lead ON lead_event (lead_id, created_at);

-- =====================================================================================
-- 8. Analitika pretrage
-- =====================================================================================

CREATE TABLE search_log
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    query_hash    TEXT        NOT NULL,
    params        JSONB       NOT NULL,
    result_count  INT         NOT NULL DEFAULT 0,
    duration_ms   INT         NOT NULL DEFAULT 0,
    cache_hit     BOOLEAN     NOT NULL DEFAULT FALSE,
    session_hash  TEXT,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_search_log_created ON search_log (created_at DESC);
CREATE INDEX idx_search_log_hash ON search_log (query_hash);

CREATE TABLE offer_click
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offer_id    BIGINT      NOT NULL REFERENCES offer (id) ON DELETE CASCADE,
    agency_id   BIGINT      NOT NULL REFERENCES agency (id) ON DELETE CASCADE,
    session_hash TEXT,
    created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX idx_offer_click_offer ON offer_click (offer_id, created_at DESC);
